title:            Center for Spatial and Textual Analysis
tagline:          "CESTA"
description:      "The Center for Spatial and Textual Analysis (CESTA) is comprised of the Spatial History Project, Humanities+Design, and the Literary Lab. This interdisciplinary collective of labs operates independently of any one particular home department, and is organizationally housed within the Dean of Research at Stanford University."
# Site domain goes here. Leave localhost server or blank when working locally.
url:

# Owner/author information
owner:
  name:           Center for Spatial and Textual Analysis
  email:
  phone:          "(650) 721-1385"
  fax:            "(650) 725-5916"
  twitter:        "cesta"
  facebook:       "cesta.stanford"

future:           true
lsi:              false
highlighter:      pygments
markdown:         kramdown
# http://jekyllrb.com/docs/permalinks/
permalink:        /:year/:month/:day/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "codekit-config.json", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "Gruntfile.js", "package.json"]
